trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
      targetType: "inline"
      script: 'sh -c "$(curl -fsSL https://get.testcontainers.cloud/bash)"'
  env:
      TC_CLOUD_TOKEN: $(TC_CLOUD_TOKEN)
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    ./mvnw verify
  displayName: 'Build with Maven'
